---
roles:
  # Install a role from Ansible Galaxy.
  - src: https://github.com/florianutz/ubuntu2004_cis.git
  - src: https://github.com/trallnag/ansible-role-endlessh.git
  - src: https://github.com/geerlingguy/ansible-role-php-versions
  - src: https://github.com/geerlingguy/ansible-role-php
  - src: https://github.com/geerlingguy/ansible-role-apache
  - src: https://github.com/geerlingguy/ansible-role-mysql
