---

- name: "Ensure we have a staging repo for deployment - where we push our local code to and where we pull from to deploy"
  file:
    path: "/var/repo"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: "Setup staging repo for deployment - where we push our local code to and where we pull from to deploy"
  file:
    path: "/var/repo/{{ site_short_name }}"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0770

- name: "Initialize empty git repo if it does not exist"
  command:
    cmd: git init --bare
    chdir: "/var/repo/{{ site_short_name }}"

- name: update permissions
  file:
    path: "/var/repo/{{ site_short_name }}"
    state: directory
    recurse: yes
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0770
  tags: permissions

- name: "Setup cake base"
  file:
    path: "/var/www/{{ site_short_name }}/"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: permissions

- name: "Setup cake base html"
  file:
    path: "/var/www/{{ site_short_name }}/html"
    state: directory
    owner: "{{ main_user }}"
    group: root
    mode: 0755
  tags: permissions

- name: Git checkout cakephp code
  ansible.builtin.git:
    repo: "/var/repo/{{ site_short_name }}"
    dest: "/var/www/{{ site_short_name }}/html/{{ site_short_name }}"

- name: update permissions cakephp root
  file:
    path: "/var/www/{{ site_short_name }}/html/{{ site_short_name }}"
    state: directory
    recurse: yes
    owner: "{{ main_user }}"
    group: www-data
    mode: 0750
  tags: 
    - permissions

- name: deploy code
  command:
    cmd: "./{{ selected_env }}_deploy.sh"
    chdir: "/var/www/{{ site_short_name }}/html/{{ site_short_name }}"
  tags: 
    - deploy

- name: update permissions cakephp tmp
  file:
    path: "/var/www/{{ site_short_name }}/html/{{ site_short_name }}/tmp"
    state: directory
    recurse: yes
    owner: "{{ main_user }}"
    group: www-data
    mode: 0760
  tags: 
    - permissions

- name: update permissions cakephp logs
  file:
    path: "/var/www/{{ site_short_name }}/html/{{ site_short_name }}/logs"
    state: directory
    recurse: yes
    owner: "{{ main_user }}"
    group: www-data
    mode: 0760
  tags: 
    - permissions
